name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:21.10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU & Clang
        run: apt update && apt install -y qemu qemu-system-x86 clang-13 make
      - name: Test
        run: make test CXX=clang++-13
